// Package docs GENERATED BY THE COMMAND ABOVE; DO NOT EDIT
// This file was generated by swaggo/swag
package docs

import (
	"bytes"
	"encoding/json"
	"strings"
	"text/template"

	"github.com/swaggo/swag"
)

var doc = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/login": {
            "put": {
                "description": "사용자 로그인 하는 API 입니다.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "사용자 로그인 하는 API",
                "parameters": [
                    {
                        "type": "string",
                        "description": "사용자 계정",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "사용자 비밀번호",
                        "name": "password",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/api/v1/group": {
            "get": {
                "description": "그룹 리스트를 조회를 위한 API 입니다.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "그룹 리스트를 조회 하는 API",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            },
            "delete": {
                "description": "그룹을 삭제하기 위한 API 입니다.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "그룹을 삭제하는 API",
                "parameters": [
                    {
                        "type": "string",
                        "description": "사용자 계정",
                        "name": "groupName",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/api/v1/group/:groupName": {
            "get": {
                "description": "그룹 리스트를 조회를 위한 API 입니다.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "그룹 리스트를 조회 하는 API",
                "parameters": [
                    {
                        "type": "string",
                        "description": "사용자 계정",
                        "name": "groupName",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/api/v1/group/:groupName/:userName": {
            "put": {
                "description": "그룹을 삭제하기 위한 API 입니다.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "그룹을 삭제하는 API",
                "parameters": [
                    {
                        "type": "string",
                        "description": "사용자를 추가할 그룹 이름",
                        "name": "groupName",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "그룹에 추가할 사용자 계정",
                        "name": "userName",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            },
            "delete": {
                "description": "그룹에서 유저를 삭제하는 API 입니다.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "그룹에서 유저를 삭제하는 API",
                "parameters": [
                    {
                        "type": "string",
                        "description": "사용자를 삭제할 그룹 이름",
                        "name": "groupName",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "그룹에 삭제할 사용자 계정",
                        "name": "userName",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/api/v1/instance": {
            "put": {
                "description": "워크스페이스의 instance 를 추가하는 API 입니다.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "워크스페이스의 instance 를 추가하는 API",
                "parameters": [
                    {
                        "type": "string",
                        "description": "UUID",
                        "name": "uuid",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "워크스페이스에 추가할 Instance 수량",
                        "name": "quantity",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            },
            "post": {
                "description": "instance 에 사용자를 할당하는 API 입니다.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "instance 에 사용자를 할당하는 API",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Instance UUID",
                        "name": "instanceUuid",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Instance 에 할당할 userName",
                        "name": "username",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/api/v1/instance/:action/:instanceUuid": {
            "patch": {
                "description": "instance 의 상태를 변경하는 API 입니다.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "instance 의 상태 변경하는 API",
                "parameters": [
                    {
                        "type": "string",
                        "description": "action 해당 값은 [VMStart, VMStop, VMDestroy] 으로 보내야 합니다.",
                        "name": "action",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Instance UUID",
                        "name": "instanceUuid",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/api/v1/instance/detail/:instanceUuid": {
            "get": {
                "description": "워크스페이스의 instance 를 추가하는 API 입니다.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "워크스페이스의 instance 를 추가하는 API",
                "parameters": [
                    {
                        "type": "string",
                        "description": "instance UUID",
                        "name": "instanceUuid",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/api/v1/logout": {
            "get": {
                "description": "사용자 로그아웃 하는 API 입니다.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "사용자 로그아웃 하는 API",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/api/v1/offering": {
            "get": {
                "description": "템플릿, 서비스 오퍼링, 디스크 오퍼링 정보를 Mold 에서 조회하여 제공하는 API 입니다.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "템플릿 및 각종 오퍼링을 조회하는 API",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/api/v1/token": {
            "get": {
                "description": "사용자 토큰을 조회를 위한 API 입니다.\n해더에 로그인시 생성된 토큰값을 \"Authorization\" 키값에 넣어주시면 됩니다.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "사용자 토큰을 조회하는 API",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/api/v1/user": {
            "get": {
                "description": "사용자 리스트를 조회를 위한 API 입니다.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "사용자 리스트를 조회 하는 API",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            },
            "put": {
                "description": "사용자 생성을 위한 API 입니다.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "사용자 생성하는 하는 API",
                "parameters": [
                    {
                        "type": "string",
                        "description": "사용자 계정",
                        "name": "username",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "사용자 계정 비밀번호",
                        "name": "password",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "사용자 전화번호",
                        "name": "phone",
                        "in": "path"
                    },
                    {
                        "type": "string",
                        "description": "사용자 이메일",
                        "name": "email",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "사용자 성",
                        "name": "firstName",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "사용자 이름",
                        "name": "lastName",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "사용자 직급",
                        "name": "title",
                        "in": "path"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/api/v1/user/:username": {
            "get": {
                "description": "사용자 상세 조회를 위한 API 입니다.\n해더에 로그인시 생성된 토큰값을 \"Authorization\" 키값에 넣어주시면 됩니다.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "사용자 상세조회 하는 API",
                "parameters": [
                    {
                        "type": "string",
                        "description": "사용자 계정",
                        "name": "username",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/api/v1/workspace": {
            "get": {
                "description": "워크 스페이스 리스트를 조회하는 API 입니다.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "워크스페이스 리스트를 조회하는 API",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            },
            "put": {
                "description": "워크스페이를 추가하는 API 입니다.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "워크스페이스를 추가하는 API",
                "parameters": [
                    {
                        "type": "string",
                        "description": "워크스페이스 이름",
                        "name": "name",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "워크스페이스 설명",
                        "name": "description",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "워크스페이스 타입(Desktop or Application)",
                        "name": "type",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "워크스페이스에서 사용할 Compute offering UUID",
                        "name": "computeOfferingUuid",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "워크스페이스에서 사용할 Template UUID",
                        "name": "templateUuid",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "boolean",
                        "description": "워크스페이스에서 Shard 여부 전용이면 'false', 공용이면 'true'",
                        "name": "shared",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/api/v1/workspace/:workspaceUuid": {
            "get": {
                "description": "워크 스페이스 리스트를 조회하는 API 입니다.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "워크스페이스 리스트를 조회하는 API",
                "parameters": [
                    {
                        "type": "string",
                        "description": "워크스페이스 UUID",
                        "name": "workspaceUuid",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/api/v1/workspaceAgent": {
            "post": {
                "description": "워크스페이를 추가하는 API 입니다.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "워크스페이스를 추가하는 API",
                "parameters": [
                    {
                        "type": "string",
                        "description": "UUID",
                        "name": "uuid",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "async job UUID",
                        "name": "asyncJobId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "workspace or instance",
                        "name": "type",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        }
    }
}`

type swaggerInfo struct {
	Version     string
	Host        string
	BasePath    string
	Schemes     []string
	Title       string
	Description string
}

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = swaggerInfo{
	Version:     "",
	Host:        "",
	BasePath:    "",
	Schemes:     []string{},
	Title:       "",
	Description: "",
}

type s struct{}

func (s *s) ReadDoc() string {
	sInfo := SwaggerInfo
	sInfo.Description = strings.Replace(sInfo.Description, "\n", "\\n", -1)

	t, err := template.New("swagger_info").Funcs(template.FuncMap{
		"marshal": func(v interface{}) string {
			a, _ := json.Marshal(v)
			return string(a)
		},
		"escape": func(v interface{}) string {
			// escape tabs
			str := strings.Replace(v.(string), "\t", "\\t", -1)
			// replace " with \", and if that results in \\", replace that with \\\"
			str = strings.Replace(str, "\"", "\\\"", -1)
			return strings.Replace(str, "\\\\\"", "\\\\\\\"", -1)
		},
	}).Parse(doc)
	if err != nil {
		return doc
	}

	var tpl bytes.Buffer
	if err := t.Execute(&tpl, sInfo); err != nil {
		return doc
	}

	return tpl.String()
}

func init() {
	swag.Register(swag.Name, &s{})
}
